//// AudioBackendTest.cpp
#include "pch.h"  // Precompiled header (auto-generated by VS)
//#include "AudioBackend.h"
//#include <cmath>
//#include <thread>
//#include <chrono>
//#include "CppUnitTest.h"
//
//using namespace Microsoft::VisualStudio::CppUnitTestFramework;
//
//namespace AudioBackendTests
//{
//    TEST_CLASS(AudioBackendUnitTests)
//    {
//    public:
//        TEST_METHOD(Play440HzTone_ProducesSound)
//        {
//            AudioBackend backend;
//
//            const int sampleRate = 44100;
//            const int durationMs = 1000;  // 1 second
//            const float frequency = 440.0f; // A4
//
//            Assert::IsTrue(backend.Initialize(sampleRate, 1), L"Failed to initialize AudioBackend");
//
//            const size_t totalSamples = static_cast<size_t>(sampleRate) * durationMs / 1000;
//            const size_t chunkSize = AudioBackend::SAMPLES_PER_BUFFER; // 2048
//            const double twoPi = 2.0 * 3.14159265358979323846;
//
//            Logger::WriteMessage("Submitting 1 second of 440 Hz tone...\n");
//
//            for (size_t start = 0; start < totalSamples; start += chunkSize)
//            {
//                std::vector<float> chunk(chunkSize, 0.0f);
//                size_t samplesToFill = min(chunkSize, totalSamples - start);
//
//                for (size_t i = 0; i < samplesToFill; ++i)
//                {
//                    double t = (start + i) / double(sampleRate);
//                    chunk[i] = 0.2f * static_cast<float>(std::sin(t * twoPi * frequency));
//                }
//
//                backend.SubmitSamples(chunk.data(), chunk.size());
//
//                // Prevent producer from outrunning consumer too much
//                std::this_thread::sleep_for(std::chrono::milliseconds(5));
//            }
//
//            // Wait for playback to finish
//            const auto timeout = std::chrono::steady_clock::now() + std::chrono::seconds(3);
//            while (backend.GetQueuedSampleCount() > 0 || backend.IsInitialized())
//            {
//                if (std::chrono::steady_clock::now() > timeout)
//                {
//                    Assert::Fail(L"Timeout: Audio did not finish playing within 3 seconds.");
//                    break;
//                }
//                std::this_thread::sleep_for(std::chrono::milliseconds(10));
//            }
//
//            backend.Shutdown();
//            Logger::WriteMessage("Tone finished playing.\n");
//        }
//    };
//}